// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reader.Api.Infrastructure.DatabaseConfig;

#nullable disable

namespace Reader.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ReaderDbContext))]
    [Migration("20260904210831_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reader.Api.Domain.Entities.LibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LibraryItems", (string)null);
                });

            modelBuilder.Entity("Reader.Api.Domain.Entities.ReadingProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryItemId");

                    b.ToTable("ReadingProgresses", (string)null);
                });

            modelBuilder.Entity("Reader.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Reader.Api.Domain.Entities.LibraryItem", b =>
                {
                    b.OwnsOne("Reader.Api.Domain.ValueObjects.MangaReference", "Manga", b1 =>
                        {
                            b1.Property<Guid>("LibraryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CoverUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("MangaCoverUrl");

                            b1.Property<string>("OriginalLanguage")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("MangaOriginalLanguage");

                            b1.Property<DateTimeOffset>("SnapshotUpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("MangaSnapshotUpdatedAt");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("MangaTitle");

                            b1.HasKey("LibraryItemId");

                            b1.ToTable("LibraryItems");

                            b1.WithOwner()
                                .HasForeignKey("LibraryItemId");

                            b1.OwnsOne("Reader.Api.Domain.ValueObjects.ExternalResourceId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("MangaReferenceLibraryItemId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Provider")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("MangaProvider");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("MangaExternalId");

                                    b2.HasKey("MangaReferenceLibraryItemId");

                                    b2.ToTable("LibraryItems");

                                    b2.WithOwner()
                                        .HasForeignKey("MangaReferenceLibraryItemId");
                                });

                            b1.Navigation("Id")
                                .IsRequired();
                        });

                    b.Navigation("Manga")
                        .IsRequired();
                });

            modelBuilder.Entity("Reader.Api.Domain.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Reader.Api.Domain.Entities.LibraryItem", null)
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("LibraryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Reader.Api.Domain.ValueObjects.ChapterReference", "Chapter", b1 =>
                        {
                            b1.Property<Guid>("ReadingProgressId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ChapterLanguage");

                            b1.Property<string>("Number")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ChapterNumber");

                            b1.Property<string>("Title")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("ChapterTitle");

                            b1.Property<string>("Volume")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("ChapterVolume");

                            b1.HasKey("ReadingProgressId");

                            b1.ToTable("ReadingProgresses");

                            b1.WithOwner()
                                .HasForeignKey("ReadingProgressId");

                            b1.OwnsOne("Reader.Api.Domain.ValueObjects.ExternalResourceId", "Id", b2 =>
                                {
                                    b2.Property<Guid>("ChapterReferenceReadingProgressId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Provider")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("ChapterProvider");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("ChapterExternalId");

                                    b2.HasKey("ChapterReferenceReadingProgressId");

                                    b2.ToTable("ReadingProgresses");

                                    b2.WithOwner()
                                        .HasForeignKey("ChapterReferenceReadingProgressId");
                                });

                            b1.Navigation("Id")
                                .IsRequired();
                        });

                    b.Navigation("Chapter")
                        .IsRequired();
                });

            modelBuilder.Entity("Reader.Api.Domain.Entities.LibraryItem", b =>
                {
                    b.Navigation("ReadingProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
